version: "3.8"
services:
  front:
    build:
      context: ""
    command: >
      sh -c "
            # DJANGO_SUPERUSER_PASSWORD=admin python manage.py createsuperuser --username admin --email admin@email.com --noinput &&
            # python manage.py makemigrations &&  
            # python manage.py migrate &&
            # python manage.py makemigrations pageapp &&      
            python manage.py migrate &&
            gunicorn studyboard.wsgi:application --env DJANGO_SETTINGS_MODULE=fdhomepage.settings.local --bind 0.0.0.0:3000"
    container_name: studyboard-local
    environment:
      TZ: Asia/Seoul
    ports:
      - '3000:3000'

networks:
  default:
