version: "3"
services:
  front:
    build:
      context: ""
      command: >
        sh -c "
            python manage.py makemigrations &&      
            python manage.py migrate &&
            # DJANGO_SUPERUSER_PASSWORD=admin python manage.py createsuperuser --username admin --email admin@email.com --noinput &&
            gunicorn studyboard.wsgi:application --env DJANGO_SETTINGS_MODULE=studyboard.settings.production --bind 0.0.0.0:3000"   
    restart: always
    container_name: studyboard-prod-v1
    environment:
      TZ: Asia/Seoul
      VIRTUAL_HOST: www.studyboard.info, studyboard.info
      LETSENCRYPT_HOST: www.studyboard.info, studyboard.info
    networks:
      - nginx-proxy
networks:
  nginx-proxy:
    external: true