version: "3.8"
services:
  front:
    build:
      context: ""
    command: >
      sh -c "
            python manage.py makemigrations &&      
            python manage.py migrate &&
            python manage.py migrate && 
            # DJANGO_SUPERUSER_PASSWORD=admin python manage.py createsuperuser --username admin --email admin@email.com --noinput &&
            gunicorn studyboard.wsgi:application --bind 0.0.0.0:3000"
    container_name: studyboard-local
    environment:
      TZ: Asia/Seoul
    ports:
      - '3000:3000'

networks:
  default:
