version: "3.8"
services:
  web:
    build: studyboard/studyboard
    command: python manage.py runserver 0.0.0.0:3000
    container_name: studyboard-local
    environment:
      TZ: Asia/Seoul
    ports:
      - '3000:3000'
