version: "3"
services:
  front:
    build:
      context: .
    restart: always
    container_name: studyboard_prod_v1
    environment:
      TZ: Asia/Seoul
      VIRTUAL_HOST: www.studyboard.info, studyboard.info
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: www.studyboard.info, studyboard.info
    networks:
      - nginx-proxy
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
networks:
  nginx-proxy:
    external: true
