version: "3.8"
services:
  front:
    build:
      context: .
    container_name: studyboard_local
    environment:
      TZ: Asia/Seoul
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
      