version: "3"

services:
  db:
    container_name: dbms-v1
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      # - ./db/initdb.d/initdb.d/db_tables.sql:/docker-entrypoint-initdb.d/1.sql
      # - ./db/initdb.d/db_triggers.sql:/docker-entrypoint-initdb.d/2.sql
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always

networks:
  backend: