# Generated by Django 3.2.8 on 2021-10-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageapp', '0002_auto_20211026_1512'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritequestion',
            unique_together={('post_id', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='posttag',
            unique_together={('tag_id', 'post_id')},
        ),
        migrations.AlterUniqueTogether(
            name='replytopost',
            unique_together={('post_id', 'reply_id')},
        ),
        migrations.AlterUniqueTogether(
            name='replytoreply',
            unique_together={('source_id', 'reply_id')},
        ),
        migrations.AlterUniqueTogether(
            name='userpostlike',
            unique_together={('user_id', 'post_id')},
        ),
        migrations.AlterUniqueTogether(
            name='userreplylike',
            unique_together={('user_id', 'reply_id')},
        ),
        migrations.AlterUniqueTogether(
            name='usertag',
            unique_together={('tag_id', 'user_id')},
        ),
    ]
