version: "3.8"
services:
  front:
    build:
      context: .
    restart: always
    container_name: studyboard_prod_v1
    environment:
      TZ: Asia/Seoul
      VIRTUAL_HOST: www.studyboard.info, studyboard.info
      LETSENCRYPT_HOST: www.studyboard.info, studyboard.info
    networks:
      - nginx-proxy
networks:
  nginx-proxy:
    external: true