version: "3.8"
services:
  front:
    build:
      context: .
    restart: always
    container_name: studyboard_local_nginx
    environment:
      TZ: Asia/Seoul
      VIRTUAL_HOST: www.studyboard.local, studyboard.local
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: www.studyboard.local, studyboard.local
    networks:
      - nginx-proxy
    expose:
      - 3000
networks:
  nginx-proxy:
    external: true